### ISSUE TITLE
Where do you get redis??

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/redis-py-feedstock#1]
for redis-py to work, you need redis itself.

It wuold be nice to have a conda-forge package for redis -- particularly for Windows.

Windows is not well supported by Redis, but there are semi-official builds here:

https://github.com/MSOpenTech/redis/releases

It seems a recipe to download and install that would be pretty easy.

**Comment by kwilcox** [comment]
Do you mean an actual `redis-server` binary installed through conda?  I'd recommend using `docker` to run redis on any OS. If you need `redis-server` for testing you can use https://github.com/jamesls/fakeredis.

**Comment by ChrisBarker-NOAA** [comment]
indeed -- redis-server.

Docker may be the best option for deployment but not a great Windows (or OS-X) experience for developers.

fakeredis looks cool -- but really only useful for testing.

Also -- I"m moving toward using conda environments as kind of a micro-docker. And conda can manage arbitrary binaries -- why not redis?

I'll see what I can do...

**Comment by nehaljwani** [comment]
https://github.com/AnacondaRecipes/aggregate/blob/master/redis-feedstock/recipe/meta.yaml

**Comment by ChrisBarker-NOAA** [comment]
Nice!

But now we need Windows.....

There is the MS project:

https://github.com/MicrosoftArchive/redis

but:

* it doesn't look like it's been touched in a while (a year)
* the build instructions require point and click in VS -- annoying! though there is probably a way to script that if someone knows about Windows building...

The good part is that it is stand-alone, so doesn't have to use any particular run time environment...

Though maybe just copying binaries is easier...

**Comment by nehaljwani** [comment]
Redis 3.2.100 is available for Windows in `main` channel.
